config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  resources  :users
  resources  :follows
  resources  :events
  resources  :home
  
  # resources :notifications do
    # collection do
      # post :mark_as_read
    # end
  # end

  post 'mark_as_read',   to:"notifications#mark_as_read", as: "mark_as_read"
  get '/notifications' , to: "notifications#index",       as: "notifications"
  
  get  '/users/:id/message',   to: 'users#message',  as: 'message_user'
  post '/users/:id/follow',   to: "users#follow",   as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get '/search' , to: 'home#index' , as: 'search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  # root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  #messaging
  has_many :messagee, foreign_key: :receiver_id, class_name: 'Message'  
  has_many :senders, through: :messagee
  has_many :messaged, foreign_key: :sender_id, class_name: 'Message'
  has_many :receivers, through: :messaged
  
  #notifications
  has_many :notifiactions, foreign_key: :recipient_id

  # has_many :events, class_name: "Event"
  has_many :events


  # enables a user to follow many other users 
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  #user has many followees through the followed_users established in the line above.
  has_many :followees, through: :followed_users

  #to create reverse as above 2
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users
  

  #uploading profile images
  mount_uploader :profile_image, ProfileImageUploader
  # validates_presence_of :profile_image
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow], except: [:message]
      def message
        @user = User.find(params[:id])
        @followers = @user.followers
        @followees = @user.followees
        @notifications = Notification.where(recipient: current_user).unread
        @sender =current_user
        @receiver = @user
        @messages = Message.where(sender_id: @sender.id, receiver_id: @receiver.id).or(Message.where(sender_id: @receiver.id, receiver_id: @sender.id))
        @chat_id = [@sender.id, @receiver.id].sort.join("") #generates a unique identifier for a pair of user 

      end
      def follow
        @user = User.find(params[:id])
        current_user.followees << @user
        redirect_back(fallback_location: user_path(@user))
      end
      
      def unfollow
        @user = User.find(params[:id])
        current_user.followed_users.find_by(followee_id: @user.id).destroy
        redirect_back(fallback_location: user_path(@user))
      end
      

      # GET /users
      # GET /users.json
      def index
        @users = User.all
        @notifications = Notification.where(recipient: current_user).unread
      end
    
      # GET /users/1
      # GET /users/1.json
      def show
        @user = User.find(params[:id])
        @followers = @user.followers
        @followees = @user.followees
        @notifications = Notification.where(recipient: current_user).unread
        @sender =current_user
        @receiver = @user
        @messages = Message.where(sender_id: @sender.id, receiver_id: @receiver.id).or(Message.where(sender_id: @receiver.id, receiver_id: @sender.id))
        @chat_id = [@sender.id, @receiver.id].sort.join("") #generates a unique identifier for a pair of user 

      end
    
      # GET /users/new
      def new
        @user = User.new
      end
    
      # GET /users/1/edit
      def edit
      end
    
      # POST /users
      # POST /users.json
      def create
        @user = User.new(user_params)
    
        respond_to do |format|
          if @user.save
            format.html { redirect_to @user, notice: 'user was successfully created.' }
            format.json { render :show, status: :created, location: @user }
          else
            format.html { render :new }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # PATCH/PUT /users/1
      # PATCH/PUT /users/1.json
      def update
        respond_to do |format|
          if @user.update(user_params)
            format.html { redirect_to @user, notice: 'user was successfully updated.' }
            format.json { render :show, status: :ok, location: @user }
          else
            format.html { render :edit }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      end
    
      # DELETE /users/1
      # DELETE /users/1.json
      def destroy
        @user.destroy
        respond_to do |format|
          format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_user
          @user = User.find(params[:id])
        end
    
        # Only allow a list of trusted parameters through.
        def user_params
          params.require(:user).permit(:name, :email, :profile_image, :reciever_id)
        end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
          <i class="mdi mdi-account-multiple"></i>
        </span> Users
      </h3>
    </div>
    <% @users.each do |user|%>
      <% if user.id != current_user.id %>
        <%= user.name%> 
        <%= link_to 'show', user_path(user)%>
        <%= link_to 'chat', message_user_path(user) %>
        <br/>
      <% end %>  
    <% end %>
    

app/views/users/message.html.erb
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white mr-2">
                <i class="mdi mdi-account-multiple"></i>
                </span> Users
            </h3>
        </div>
        <h2><%=@sender.name %> contacting <%=@receiver.name%></h2>
        <div id="messages">
            <% @messages.each do |message| %>
                <p><%= message.sender.name %>: <%= message.text %></p>
            <% end %>
        </div>
        
        <%= form_tag messages_path  do %>
            <div>
                <%= text_field_tag :message, nil ,  placeholder: 'Type message here...', class: 'form-control' %>
                <%= hidden_field_tag "receiver_id", @receiver.id %>
                <%= hidden_field_tag "sender_id", @sender.id %>
                <%= hidden_field_tag "chat_id", @chat_id %>
                <%= submit_tag "Send", data: { disable_with: false } %>
            </div>
        <% end %>
        
        
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="panel panel-primary">
                        <div class="panel-heading" id="accordion">
                            <span class="glyphicon glyphicon-comment"></span> Chat
                            <div class="btn-group pull-right">
                                <a type="button" class="btn btn-default btn-xs" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                    <span class="glyphicon glyphicon-chevron-down"></span>
                                </a>
                            </div>
                        </div>
                    <div class="panel-collapse collapse" id="collapseOne">
                        <div class="panel-body">
                            <ul class="chat">
                                <li class="left clearfix"><span class="chat-img pull-left">
                                    <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
                                </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                                <span class="glyphicon glyphicon-time"></span>12 mins ago</small>
                                        </div>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                            dolor, quis ullamcorper ligula sodales.
                                        </p>
                                    </div>
                                </li>
                                <li class="right clearfix"><span class="chat-img pull-right">
                                    <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
                                </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>13 mins ago</small>
                                            <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                        </div>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                            dolor, quis ullamcorper ligula sodales.
                                        </p>
                                    </div>
                                </li>
                                <li class="left clearfix"><span class="chat-img pull-left">
                                    <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
                                </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                                <span class="glyphicon glyphicon-time"></span>14 mins ago</small>
                                        </div>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                            dolor, quis ullamcorper ligula sodales.
                                        </p>
                                    </div>
                                </li>
                                <li class="right clearfix"><span class="chat-img pull-right">
                                    <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
                                </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>15 mins ago</small>
                                            <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                        </div>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                            dolor, quis ullamcorper ligula sodales.
                                        </p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="panel-footer">
                            <div class="input-group">
                                <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
                                <span class="input-group-btn">
                                    <button class="btn btn-warning btn-sm" id="btn-chat">
                                        Send</button>
                                </span>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
   
        
        </div>

app/views/users/show.html.erb
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
          <i class="mdi mdi-account-card-details"></i>
        </span> User profile
      </h3>
      <!-- Breadcrumb -->
      <nav aria-label="breadcrumb" class="main-breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "users", users_path %></li>
          <li class="breadcrumb-item active" aria-current="page">user Profile</li>
        </ol>
      </nav>
      <!-- /Breadcrumb -->
    </div>
    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <%# <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150"> %>
              <img src="<%=@user.profile_image%>" alt="Profile_image" class="rounded-circle" width="150"/>
              <%# <%= image_tag(@user.profile_image_url(:thumbnail), :alt =>"Profile_image",class:"rounded-circle", style:" width:150px;") %> 
              <div class="mt-3 ">
                <h4><%=@user.name%></h4>
                <p class="text-secondary mb-1">Bio......</p>
                <p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p>
                
                <div class='row '>
                  <div class='mr-auto'>
                    <% if @user.id == current_user.id %>
                      <%= button_to "Logout", '/logout', method: :post , class: "btn btn-primary btn-sm" %>
                    <% elsif current_user.followees.include?(@user) %>
                      <%= button_to "Unfollow", unfollow_user_path, method: "POST" , class: "btn btn-primary btn-sm "%>
                    <% else %>
                      <%= button_to " Follow  ", follow_user_path, method: "POST" , class: "btn btn-primary btn-sm" %>
                    <% end%>
                  </div>
                  <div class='ml-auto'>
                    <button class="btn btn-outline-primary  btn-sm">Message</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card mt-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
              <span class="text-secondary">https://bootdey.com</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
              <span class="text-secondary">bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
              <span class="text-secondary">@bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
              <span class="text-secondary">bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
              <span class="text-secondary">bootdey</span>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Full Name</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                <%=@user.name.capitalize%>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Email</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                <%= @user.email%>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Phone</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                (239) 816-9029
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Mobile</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                (320) 380-4539
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Address</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                Bay Area, San Francisco, CA
              </div>
            </div>
          </div>
        </div>
        <div class="row gutters-sm">
          <div class="col-sm-6 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <table class="table table-hover">
                  <h4 class="card-title">Followers</h4>
                    <%# <p class="card-description"> Add class <code>.table-hover</code> %>
                    </p>
                  <thead>
                    <tr>
                      <th>User</th>
                      <th>Name</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @followers.first(4).each do |f| %>
                    <tr>
                      <td class="py-1">
                        <%# <img src="images/faces-clipart/pic-1.png" alt="image" /> %>
                        <%# <%= image_tag ("faces-clipart/pic-1.png"), class:"mr-2", alt:"image" %> 
                        <%= image_tag(f.profile_image_url(:thumbnail), :alt =>"",class:"mr-2") %>
                      </td>
                      <td><%= f.name %></td>
                      <td>
                        <%# <% if f.id == current_user.id %> 
                          <%= link_to "View", user_path(f),method: :get , class: "btn btn-primary btn-sm" %>
                        <%# <% elsif f.followees.include?(@user) %> 
                        <%# <%= button_to "Unfollow", unfollow_user_path, method: "POST" , class: "btn btn-primary btn-sm "%> 
                        <%# <% else %> 
                          <%# <%= button_to " Follow  ", follow_user_path, method: "POST" , class: "btn btn-primary btn-sm" %> 
                        <%# <% end%> 
                      </td>
                    </tr>
                  <% end %>  
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-sm-6 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <table class="table table-hover">
                  <h4 class="card-title">Following</h4>
                    <%# <p class="card-description"> Add class <code>.table-hover</code> %>
                    </p>
                  <thead>
                    <tr>
                      <th>User</th>
                      <th>Name</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @followees.first(4).each do |f| %>
                    <tr>
                      <td class="py-1">
                        <%# <img src="images/faces-clipart/pic-1.png" alt="image" /> %>
                        <%# <%= image_tag ("faces-clipart/pic-1.png"), class:"mr-2", alt:"image" %> 
                        <%= image_tag(f.profile_image_url(:thumbnail), :alt =>"Profile_image",class:"mr-2") %>
                      </td>
                      <td><%= f.name %></td>
                      <td>
                        <%# <% if f.id == current_user.id %> 
                          <%= link_to "View", user_path(f),method: :get , class: "btn btn-primary btn-sm" %>
                        <%# <% elsif f.followees.include?(@user) %> 
                        <%# <%= button_to "Unfollow", unfollow_user_path, method: "POST" , class: "btn btn-primary btn-sm "%> 
                        <%# <% else %> 
                          <%# <%= button_to " Follow  ", follow_user_path, method: "POST" , class: "btn btn-primary btn-sm" %> 
                        <%# <% end%> 
                      </td>
                    </tr>
                  <% end %>  
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div>
    <h2><%=@sender.name %> contacting <%=@receiver.name%></h2>
    <div id="messages">
        <% @messages.each do |message| %>
            <p><%= message.sender.name %>: <%= message.text %></p>
        <% end %>
    </div>
    
    <%= form_tag messages_path  do %>
        <div>
            <%= text_field_tag :message, nil ,  placeholder: 'Type message here...', class: 'form-control' %>
            <%= hidden_field_tag "receiver_id", @receiver.id %>
            <%= hidden_field_tag "sender_id", @sender.id %>
            <%= hidden_field_tag "chat_id", @chat_id %>
            <%= submit_tag "Send", data: { disable_with: false } %>
        </div>
    <% end %>
</div>
        </div>
      </div>
    </div>
   </div>