config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  resources  :users
  resources  :follows
  resources  :events
  resources  :home
  
  # resources :notifications do
    # collection do
      # post :mark_as_read
    # end
  # end

  post 'mark_as_read',   to:"notifications#mark_as_read", as: "mark_as_read"
  get '/notifications' , to: "notifications#index",       as: "notifications"
  
  get  '/users/:id/message',   to: 'users#message',  as: 'message_user'
  post '/users/:id/follow',   to: "users#follow",   as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get '/search' , to: 'home#index' , as: 'search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  # root to: "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
  # belongs_to :user
  belongs_to :user

  # attr_accessible :location, :latitude, :longitude
  geocoded_by :location
  after_validation :geocode, :if => :location_changed?

  #uploading profile images
  mount_uploader :image, ProfileImageUploader

  def self.search(params)
    events = all
    if params[:search].present?
      events = events.where("name like :search", search: "%#{params[:search]}" ) 
    end
    events
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :combine_location , only: [:create, :update]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @notifications = Notification.where(recipient: current_user).unread
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @notifications = Notification.where(recipient: current_user).unread
  end

  # GET /events/new
  def new
    @event = Event.new
    @notifications = Notification.where(recipient: current_user).unread
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)
    respond_to do |format|
      if @event.save
        current_user.followers.each do |user|
          Notification.create(recipient: user, actor: current_user, action:'Posted', notifiable: @event)
        end
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    #convert location array into string
    def combine_location
        params[:event][:location] = params[:event][:location].join(',')
        # params[:event].delete('user_id')
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
      @notifications = Notification.where(recipient: current_user).unread

    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :body, :date, :status, :location, :latitude, :longitude, :image)
      # , :state, :city, :street, :country
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/--form.html.erb
<div class="row">
  <h2> <%= controller_name %> </h2>
    <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
       <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
             <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
             <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :body %>
        <%= form.text_area :body %>
       </div>

       <div class="field">
         <%= form.label :date %>
         <%= form.datetime_select :date %>
       </div>
       
       <div class="field">
         <%= form.label :street %>
         <%= form.text_field :location, multiple: true %>
       </div>

       <div class="field">
         <%= form.label :city %>
         <%= form.text_field :location, multiple: true %>
       </div>

       <div class="field">
         <%= form.label :state %>
         <%= form.text_field :location, multiple: true %>
       </div>
         <div class="field">
         <%= form.label :country %>
         <%= form.text_field :location , multiple: true%>
       </div>
       <%# <%= form.location.join('') %> 
      <%# <%= form.hidden_field  :location , :value => [ :street, :city, :state, :country].join(',') %> 
       
      <div class="field">
        <%= form.label :status %>
        <%= form.check_box :status %>
      </div>

      <div class="actions">
         <%= form.submit %>
      </div>
    <% end %>
</div> 

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
          <i class="mdi mdi-calendar"></i>
        </span> Events
       </h3>
    </div>
    <%# <p id="notice"><%= notice %></p> 



    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Body</th>
            <th>Date</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.body %></td>
            <td><%= event.date %></td>
            <td><%= event.status %></td>
            <td><%= link_to 'Show', event %></td>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Event', new_event_path %>
 
 </div>

app/views/events/nearby.erb
<p>
      <strong>Name:</strong>
      <%= @event.name %>
    </p>

    <p>
     <strong>Body:</strong>
     <%= @event.body %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @event.date %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @event.location %>
    </p>

    <p>
      <strong>Latitude:</strong>
      <%= @event.latitude %>
    </p>

    <p>
      <strong>Longitude:</strong>
      <%= @event.longitude %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @event.status %>
    </p>
    <p>
      <strong>user:</strong>
      <%= @event.user.id %>
    </p>
     
     
    <div>
     <%= image_tag "https://dev.virtualearth.net/REST/v1/Imagery/Map/Road/#{@event.latitude},#{@event.longitude}/11?mapSize=500,500&pp=#{@event.latitude},#{@event.longitude};66&mapLayer=Basemap,Buildings&key=#{ENV['bing_api_key']}"%> 
    </div>
    
    <p>
    <ul>
    <li><strong>Nearby Events</strong></li>
      <% for event in @event.nearbys(31) %>
       <li><%= link_to event.name, event %>, <%= event.location%> (<%= event.distance.round(2)*1.60934 %> km)</li>
      <% end %>
    </ul>
    
    </p>
   


    <%= link_to 'Edit', edit_event_path(@event) %> |
    <%= link_to 'Back', events_path %>

</div>

app/views/events/new.html.erb
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
          <i class="mdi mdi-calendar-plus"></i>
        </span> Add event
       </h3>
    </div>
     <%= render 'form', event: @event %>

     <%# <%= link_to 'Back', events_path %>
     </div>

app/views/events/show.html.erb
<div class="main-panel">
  <div class="content-wrapper"  style="background-image: url('<%= @event.image %>');">
    <div class="page-header">
      <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
          <i class="mdi mdi-calendar"></i>
        </span> <%= @event.name %>
        </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/events">Events</a></li>
            <li class="breadcrumb-item active" aria-current="page"><%= @event.name %></li>
          </ol>
        </nav>
    </div>
    <div class="row" >
      <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Details</h4>
            <p class="card-description"></p>
            <div class="template-demo">
              <h4> 
                <strong>Event name:</strong>
                <%= @event.name %>
              </h4>
              <h4>
                <strong>Description:</strong>
                <%= @event.body %>
              </h4>
              <h4>
                 <strong>Location:</strong>
                 <%= @event.location.to_s.gsub(',',',  ') %>
              </h4>
              <h4>
                 <strong>Date:</strong>
                 <%= @event.date.strftime("%d-%m-%y") %>
              </h4>
              <h4>
                <strong>Time:</strong>
                 <%= @event.date.strftime("%I:%M %p") %>
               </h4>
               <h4>
                  <strong>Posted by:</strong>
                  <%= link_to  @event.user.name, user_path(@event.user) %>
               </h4>
              </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Map</h4>
            <p class="card-description"> </p>
            <div class="template-demo">
              <%= image_tag "https://dev.virtualearth.net/REST/v1/Imagery/Map/Road/#{@event.latitude},#{@event.longitude}/11?mapSize=460,300&pp=#{@event.latitude},#{@event.longitude};66&mapLayer=Basemap,Buildings&key=#{ENV['bing_api_key']}"%> 
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>

    